#!/bin/bash
source scripts/functions

export DOTFILES 
DOTFILES="$(pwd -P)"

set -e

echo ''


case $1 in
    "install")
        source ./scripts/install
        ;;
    "update")
        source ./scripts/update
        ;;
    "check")
        shellcheck ./run -x scripts/**/*
        ;;
    "link")
        ./install;
        ;;
    "settings")
        source scripts/os-settings;
        ;;
    "git-init")
        source scripts/git;
        ;;
    *) 
        error "invalid mode"
        header "supported modes"
        info "install"
        info "git-init"
        info "settings"
        info "update"
        info "link"
        info "check"
esac

echo ''