#!/bin/sh
export DOTFILES 
DOTFILES="~/.dotfiles"

. ~/.dotfiles/scripts/functions

set -e

echo ''


case $1 in
    "install")
        source ~/.dotfiles/scripts/install
        ;;
    "update")
        source ~/.dotfiles/scripts/update
        ;;
    "check")
        shellcheck ./run -x scripts/**/*
        ;;
    "link")
        ~/.dotfiles/install;
        ;;
    "settings")
        source ~/.dotfiles/scripts/os-settings;
        ;;
    "git-init")
        source ~/.dotfiles/scripts/git;
        ;;
    *) 
        error "invalid mode"
        header "supported modes"
        info "install"
        info "git-init"
        info "settings"
        info "update"
        info "link"
        info "check"
esac

echo ''