#!/bin/bash
source scripts/functions

export DOTFILES 
DOTFILES="$(pwd -P)"

set -e

echo ''


case $1 in
    "update")
        source ./scripts/update
        ;;
    "check")
        shellcheck ./run -x scripts/*
        ;;
    "link")
        ./install;
        ;;
    "git-init")
        source scripts/git;
        ;;
    *) 
        error "invalid mode"
        header "supported modes"
        info "update"
        info "link"
        info "check"
esac

echo ''