#!/bin/sh

info () { printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"; }
user () { printf "\r  [ \033[0;33m??\033[0m ] %s\n" "$1"; }
header()   { echo "\n\033[1m$*\033[0m"; }
success()  { echo " \033[1;32m✔\033[0m  $*"; }
error()    { echo " \033[1;31m✖\033[0m  $*"; }
info()     { echo " \033[1;34m➜\033[0m  $*"; }
ok()     { success 'Done'; }

brew_it() {
    if brew list -1 | grep -q "^$1\$"; then
        echo "$1 is already installed"
    else
        info "Installing $*"
            brew install "$@"
        ok
    fi
}

cask_it() {
    if brew cask list -1 | grep -q "^$1\$"; then
        echo "$1 is already installed"
    else
        info "Installing $*.."
            brew cask install $@
        ok    
    fi    
}

tap_it() {
  brew tap "$1" --repair 2> /dev/null
}