#!/bin/bash
header 'Setup git workflow'

info "Setting up Github SSH key pairs."
ssh-keygen -t rsa -b 4096 -C "$git_authoremail"

info "Starting ssh-agent in the background."
eval "$(ssh-agent -s)"

info "Adding your SSH key to ssh-agent."
ssh-add ~/.ssh/id_rsa

info "Copying SSH key to your clipboard."
pbcopy < ~/.ssh/id_rsa.pub

info "Add key to github to finish setup."
echo "Press enter when ready."
read -r