#!/bin/bash

if ! command -v brew >/dev/null; 
then
 info "Installing Homebrew ..."
   curl -fsS \
     'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
   export PATH="/usr/local/bin:$PATH"
   ok
fi

[[ ! "$(command -v brew)" ]] && error "Homebrew failed to install." && return 1

info "Updating Homebrew"
    brew update
    brew upgrade
ok

brew_it git
brew tap caskroom/cask
brew tap caskroom/fonts
brew tap caskroom/versions
brew tap homebrew/bundle
brew tap homebrew/dupes
brew_it homebrew/completions/brew-cask-completion

case $2 in
    "--dev")
        source ~/.dotfiles/scripts/installs/dev
        ;;
    "--apps")
        source ~/.dotfiles/scripts/installs/apps
        ;;
    "--shell")
        source ~/.dotfiles/scripts/installs/shell
        ;;
    "--system")
        source ~/.dotfiles/scripts/installs/system
        ;;
    *)
        source ~/.dotfiles/scripts/installs/shell
        source ~/.dotfiles/scripts/installs/system
        source ~/.dotfiles/scripts/installs/apps
        source ~/.dotfiles/scripts/installs/dev
        ;;
esac
