#!/bin/bash

if ! command -v brew >/dev/null; 
then
 info "Installing Homebrew ..."
   curl -fsS \
     'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
   export PATH="/usr/local/bin:$PATH"
   ok
fi

[[ ! "$(command -v brew)" ]] && error "Homebrew failed to install." && return 1

if brew list | grep -Fq brew-cask; 
then
 info "Uninstalling old Homebrew-Cask ..."
 brew uninstall --force brew-cask
 ok
fi

info "Updating Homebrew"
    brew update
    brew upgrade
ok

brew_it git
brew tap caskroom/cask
brew tap caskroom/fonts
brew tap caskroom/versions
brew tap homebrew/bundle
brew tap homebrew/dupes

case $2 in
    "--dev")
        source scripts/installs/dev
        ;;
    "--apps")
        source scripts/installs/apps
        ;;
    "--shell")
        source scripts/installs/shell
        ;;
    "--system")
        source scripts/installs/system
        ;;
    *)
        source scripts/installs/shell
        source scripts/installs/system
        source scripts/installs/apps
        source scripts/installs/dev
        ;;
esac
