#!/bin/bash

header 'Updating software'

info "Update OS"
    sudo softwareupdate -iva
ok

info "Update brew"
    brew update; 
    brew upgrade --all; 
    brew cleanup; 
ok

info "Update android"
    android update sdk --no-ui
ok

info "Update global NPM packages"
    npm install npm -g; npm update -g
ok

info 'Update Heroku'
    heroku update
ok
info 'Update Oh My Zsh'
    upgrade_oh_my_zsh
ok

info "Update packages installed with git"
    cd ~/.oh-my-zsh/custom/themes/powerlevel9k || exit 
    git pull

    cd ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions || exit
    git pull

    cd ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting || exit
    git pull

    cd ~/.oh-my-zsh/custom/plugins/alias-tips || exit
    git pull

    cd ~/.oh-my-zsh/custom/plugins/git-aliases || exit
    git pull

    cd ~/.oh-my-zsh/custom/plugins/zsh-better-npm-completion || exit
    git pull

    cd ~/.oh-my-zsh/custom/plugins/zsh-nvm || exit
    git pull

    cd ~/.tmux/plugins/tpm || exit
    git pull
ok