#!/bin/bash

header 'Updating software'

info "Update OS"
    sudo softwareupdate -ia
ok

info "Update brew"
    brew update 
    brew upgrade --force-bottle --cleanup
    brew cleanup 
    brew cask cleanup
    brew prune
ok

info "Update global NPM packages"
    #nvm use system
    npm install npm -g 
    npm update -g
ok

info "Update pip packages"
    pip install --upgrade pip
    pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
ok

info "Update gems"
    sudo gem update --system
    sudo gem update --no-rdoc --no-ri
ok

info 'Update Oh My Zsh'
    env ZSH=$ZSH /bin/sh $ZSH/tools/upgrade.sh
ok

info "Update packages installed with git"
    cd ~/.oh-my-zsh/custom/themes/powerlevel9k || exit 
    git pull

    cd ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions || exit
    git pull

    cd ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting || exit
    git pull

    cd ~/.oh-my-zsh/custom/plugins/alias-tips || exit
    git pull

    cd ~/.oh-my-zsh/custom/plugins/git-aliases || exit
    git pull

    cd ~/.oh-my-zsh/custom/plugins/zsh-better-npm-completion || exit
    git pull

    cd ~/.oh-my-zsh/custom/plugins/zsh-nvm || exit
    git pull

    cd ~/.oh-my-zsh/custom/plugins/zsh-interactive-cd || exit
    git pull

    cd ~/.tmux/plugins/tpm || exit
    git pull
ok