#!/bin/bash

info 'Installing browsers'
    cask_it google-chrome
    cask_it google-chrome-canary
    cask_it firefox
ok

info 'Installign various usefull applications'
    cask_it alfred
    cask_it franz
    cask_it dropbox
    cask_it disk-inventory-x
    cask_it karabiner-elements
    cask_it vlc
    cask_it skype
    cask_it handbrake # video transcoder
    cask_it tunnelbear # vpn
    cask_it caffeine
    cask_it dash
    cask_it macdown
    cask_it google-drive
    cask_it hammerspoon
    cask_it vox
    cask_it acorn
ok 
