#!/bin/bash

info 'Installing browsers'
    cask_it google-chrome
    cask_it google-chrome-canary
    cask_it firefox
ok

info 'Installign various usefull applications'
    cask_it alfred
    cask_it franz
    cask_it dropbox
    cask_it karabiner-elements
    cask_it vlc
    cask_it skype
    cask_it handbrake # video transcoder
    cask_it tunnelbear # vpn
    cask_it caffeine
    cask_it dash
    cask_it macdown
    cask_it google-drive
    cask_it hammerspoon
    cask_it vox
ok 

info 'Installing from store'
    mas "App Cleaner", id: 1013897218
    mas "Keynote", id: 409183694
    mas "Numbers", id: 409203825
    mas "Pages", id: 409201541
    mas "amphetamine", id: 937984704
ok