#!/bin/bash

info 'Installing programming langs/environments'
    cask_it java
    brew_it python
    brew_it lua --with-completion
    brew_it go
    curl https://sh.rustup.rs -sSf | sh
    brew_it leiningen
    brew_it nvm
    nvm install node
    
ok

info 'Installing dev tooling'
    brew_it ctags
    brew_it git-extras
    brew_it git-flow
    brew_it hub
    cask_it charles
    brew_it wireshark --with-qt5
    brew_it imagemagick --with-webp --with-ghostscript
    brew_it shellcheck
    brew_it heroku-toolbelt
    brew_it ipcalc
    brew_it dos2unix
    brew_it watchman
    brew_it stormssh
    cask_it docker
    brew_it awscli
    brew_it exa

    brew_it maven
    brew_it gradle

    brew_it gcc

    # mtr - ping & traceroute. best.
    brew_it mtr --no-gtk

    # allow mtr to run without sudo
    mtrlocation=$(brew info mtr | grep Cellar | sed -e 's/ (.*//') #  e.g. `/Users/paulirish/.homebrew/Cellar/mtr/0.86`
    sudo chmod 4755 "$mtrlocation/sbin/mtr"
    sudo chown root "$mtrlocation/sbin/mtr"
ok

info 'Installing editors...'
    brew_it vim --with-override-system-vi
    cask_it visual-studio-code
    cask_it android-studio
    cask_it intellij-idea-ce
    cask_it rstudio
    mas install 497799835
ok

codes=(
    formulahendry.auto-close-tag
    formulahendry.auto-rename-tag
    EditorConfig.EditorConfig
    PeterJausovec.vscode-docker
    akamud.vscode-caniuse
    cssho.vscode-svgviewer
    dbaeumer.vscode-eslint
    eg2.vscode-npm-script
    fknop.vscode-npm
    keyring.Lua
    lukehoban.Go
    James-Yu.latex-workshop
    msjsdiag.debugger-for-chrome
    qinjia.view-in-browser
    robertohuertasm.vscode-icons
    eamodio.gitlens
    christian-kohler.path-intellisense
    esbenp.prettier-vscode
    2gua.rainbow-brackets
    alefragnani.bookmarks
    lamartire.git-indicators
    deerawan.vscode-dash
)

info "Installing VSCode plugins"
    for pkg in "${codes[@]}"; do
        code --install-extension "$pkg"
    done
ok
