#!/bin/bash

info 'Installing shells'
    brew_it zsh
    brew_it zsh-completions
    brew_it bash
    brew_it bash-completion
    cask_it iterm2
    brew_it thefuck
ok

info 'Configuring zsh'
if [ ! -d ~/.oh-my-zsh ];
then
  curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi

if [ ! -d ~/.oh-my-zsh/custom/themes/powerlevel10k ]; 
then
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi
if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ];
then
  git clone git://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
fi
if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ];
then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
fi  
if [ ! -d ~/.oh-my-zsh/custom/plugins/alias-tips ];
then
  git clone https://github.com/djui/alias-tips.git ~/.oh-my-zsh/custom/plugins/alias-tips
fi
if [ ! -d ~/.oh-my-zsh/custom/plugins/caniuse ];
then
  git clone https://github.com/walesmd/caniuse.plugin.zsh ~/.oh-my-zsh/custom/plugins/caniuse
fi
if [ ! -d ~/.oh-my-zsh/custom/plugins/git-aliases ];
then
  git clone https://github.com/peterhurford/git-aliases.zsh.git ~/.oh-my-zsh/custom/plugins/git-aliases
fi
if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-better-npm-completion ];
then
  git clone https://github.com/lukechilds/zsh-better-npm-completion ~/.oh-my-zsh/custom/plugins/zsh-better-npm-completion
fi
if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-nvm ];
then
  git clone https://github.com/lukechilds/zsh-nvm ~/.oh-my-zsh/custom/plugins/zsh-nvm
fi
if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ];
then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
fi

curl -L https://iterm2.com/misc/install_shell_integration_and_utilities.sh | bash
