#!/bin/bash

info 'Install system tooling'
    brew_it mas
    brew_it cmake
    brew_it the_silver_searcher # Search tool like grep, but optimized for programmers
    brew_it coreutils --with-gmp # GNU File, Shell, and Text utilities
    brew_it moreutils # Install some other useful utilities like `sponge`
    brew_it findutils --with-default-names # Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
    brew_it gnu-sed --with-default-names # Install GNU `sed`, overwriting the built-in `sed`.
    brew_it p7zip # 7zip archiver
    brew_it pigz # Parallel gzip
    brew_it zopfli # New zlib (gzip, deflate) compatible compressor
    brew_it unrar
    brew_it tree # Display directories as trees (with optional color/HTML output)
    brew_it openssl
    brew_it grc # Colorize logfiles and command output
    brew_it nmap
    brew_it wget --with-iri
    brew_it fzf #fzf is a general-purpose command-line fuzzy finder.
    brew_it htop
    brew_it grep
    brew_it openssh
    brew_it screen
    brew_it httpie
ok 

info 'Installing Quick Look plugins...'
    cask_it betterzipql
    cask_it qlcolorcode
    cask_it qlmarkdown
    cask_it qlprettypatch
    cask_it qlstephen
    cask_it quicklook-csv
    cask_it quicklook-json
    cask_it quicknfo
    cask_it suspicious-package
    cask_it webpquicklook
ok

info 'Instaling Color pickers...'
    cask_it colorpicker-developer
    cask_it colorpicker-skalacolor
ok 

info 'Installing font tools and fonts...'
    brew tap caskroom/fonts
    brew_it fontconfig
    cask_it font-source-code-pro
    cask_it font-source-sans-pro
    cask_it font-fontawesome
    cask_it font-awesome-terminal-fonts
    cask_it font-hack
    cask_it font-inconsolata-dz-for-powerline
    cask_it font-inconsolata-g-for-powerline
    cask_it font-inconsolata-for-powerline
    cask_it font-roboto-mono
    cask_it font-roboto-mono-for-powerline
    cask_it font-source-code-pro
ok
